@echo off
rem Copyright (c) 2019-2023 BUGSENG srl
rem See LICENSE.txt for details.
SetLocal EnableDelayedExpansion

rem Make sure "%GCC%" expands to GCC/x86_64 at least version 8
rem and that "%LINK32%" (resp., "%LINK64%") expand to a GCC command
rem that can link i686 (resp., x86_64) object code generated by "%GCC%" -m32
rem (resp., "%GCC%" -m64) with the C standard library.

rem Below are two possibilities (the first one commented out)
rem that we have successfully tested.

rem set PATH=c:\msys64\mingw64\bin;c:\msys64\mingw32\bin;%PATH%
rem set LINK32=c:\msys64\mingw32\bin\gcc.exe
rem set LINK64=c:\msys64\mingw64\bin\gcc.exe
rem set GCC=gcc

set "PATH=C:\Program Files\mingw-w64\x86_64-8.1.0-win32-seh-rt_v6-rev0\mingw64\bin;%PATH%"
set "LINK32=C:\Program Files (x86)\mingw-w64\i686-8.1.0-win32-dwarf-rt_v6-rev0\mingw32\bin\gcc.exe"
set "LINK64=C:\Program Files\mingw-w64\x86_64-8.1.0-win32-seh-rt_v6-rev0\mingw64\bin\gcc.exe"
set GCC=gcc

set max=767

"%GCC%" -w main.c -o a.exe
for /L %%v in (0,1,%max%) do (
  rem echo %%v
  for /f "delims=" %%a in ('a.exe %%v') do set options=%%a
  rem echo !options!
  "%GCC%" -w !options! main.c -c -o main.o
  if not "x!options:-m32=!" == "x!options!" (
    set "LINK=%LINK32%"
  ) else (
    set "LINK=%LINK64%"
  )
  "!LINK!" main.o -o %%v.out
  for /f "delims=" %%a in ('%%v.out') do set result=%%a
  rem echo !result!
  if not !result! == %%v (
    set failed=%%v
    goto failed
  )
)

echo tests 0..%max% succeeded
exit /b 0

:failed
echo test !failed! failed
exit /b 1
